### ISSUE TITLE
Data life cycle

### ISSUE THREAD

**Issue by randy554** [TimTerwijn/real-time-web-1920#1]
- In de data life cycle diagram staan twee server componenten aangegeven (Harry & Tim) maar deze zijn niet helemaal duidelijk voor mij. Heb het idee dat het om een dezelfde server component gaat met twee verschillende events. Als dit het geval is, is het een idee om één server component aan te geven  met twee event lijnen of twee data velden.

- Hoewel de data in de client component hint naar meerdere gebruikers zou het een idee kunnen zijn om dit ook visueel te laten blijken, zodat het in een oogoplsag te zien is.

- Misschien is het ook handig om aan te geven in je client component welke data je gebruikt van de API

Verder vrij duidelijk 👍

**Comment by SynthWeaver** [comment]
*Het was een fout, ik had server en client per ongeluk door elkaar gehaald.

*Ik heb het weg gehaald, nog maar een client en een server duidelijkheid. Ik heb geen behoefte aan iets visueels. Maar thanks voor de tip.

*Thanks, ik heb het er bij gezet.
